# Site settings
title: Jekyll + Python API
email: team@zeit.co
description: > # this means to ignore newlines until "baseurl:"
  Welcome to an example of Jekyll with a Python API.
baseurl: '/posts' # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
